# Generated by Django 3.2.8 on 2021-10-16 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinax_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaredMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stared', models.BooleanField(default=False, verbose_name='Stared')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stared', to='pinax_messages.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staredmessage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
