# Generated by Django 3.2.9 on 2021-11-24 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_gateway_credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='RuleConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('condition', models.TextField()),
                ('action', models.TextField()),
                ('readable_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inconditions', to='the_gateway_credentials.gatewaycredentials')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='the_rules.rule')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('rule', 'name')},
            },
        ),
    ]
