# Generated by Django 3.2.9 on 2021-11-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ruleconditions',
            unique_together={('rule', 'sequence'), ('rule', 'name')},
        ),
    ]
