# Generated by Django 3.2.9 on 2021-11-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_rules', '0002_alter_ruleconditions_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='priority',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, unique=True),
        ),
    ]
